#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Apr 15 19:31:06 2019

@author: myo
"""

import feedparser

feed = feedparser.parse('http://calendar.utexas.edu/calendar.xml')

food_list = [event.link for event in feed.entries if 'food' in event.description]